[tool.commitizen]
name = "cz_conventional_commits"
tag_format = "v$version"
version_scheme = "semver"
version = "0.4.0"
annotated_tag = true
update_changelog_on_bump = true
changelog_incremental = true
bump_message = "release $current_version â†’ $new_version [no-ci]"
version_files = [
    "setup.py"
]